// src/components/LoginForm/loginForm.svelte
<script>
	import { cubicInOut } from 'svelte/easing';
	import fadeScale from './fade-scale.js';
	import Box from '../box.svelte';
	import Button from '../button.svelte';
	import Switch from '../switch.svelte';
	import { browser } from '$app/environment';
	import { goto } from '$app/navigation';
	import { setLogStatus } from '$lib/client/state.svelte.js';
	import CropperModal from '../CopperModal/CropperModal.svelte';

	let { data } = $props();
	if (data.accessToken) {
		if (browser) {
			localStorage.setItem('accessToken', data.accessToken);
			setLogStatus({ isLoggedIn: true, accessToken: data.accessToken });
			goto('/home'); // Redirect to home page after successful login
		}
	}
	let switchActive = $state(0);
	let showModal = $state(false);
	// cropper

	let croppedImage = $state(null);
	let blob = $state(null);
	let mimeType = $state(null);
	let extenstion = {
		'image/png': 'png',
		'image/jpeg': 'jpg',
		'image/webp': 'webp'
	};

	/**
	 * @type {FileList | null}
	 */
	let avatarFile = $state(null);

	let handleSubmit = (
		/** @type {{ preventDefault: () => void; target: { parentElement: { parentElement: { parentElement: { submit: () => void; }; }; }; }; }} */ event
	) => {
		event.preventDefault();

		if (blob) {
			let file = new File([blob], `avatar.${extenstion[mimeType || 'image/png']}`, {
				type: mimeType || 'image/png'
			});
			console.log('Cropped image file:', file);
			const fileList = new DataTransfer();
			fileList.items.clear();
			fileList.items.add(file);

			avatarFile = fileList.files;

			// @ts-expect-error Element exists
			document.querySelector('input[name="avatar"]').files = avatarFile;
		}
		event.target.parentElement.parentElement.parentElement.submit();
	};
</script>

<div class="login-page">
	<Switch labels={['Connexion', 'Inscription']} bind:active={switchActive} />
	<Box>
		<form
			method="POST"
			enctype="multipart/form-data"
			action="?/{switchActive == 0 ? 'login' : 'register'}"
		>
			{#if switchActive == 1}
				<div
					class="form-line"
					transition:fadeScale={{
						delay: 0,
						duration: 400,
						easing: cubicInOut,
						baseScale: 0.5
					}}
				>
					<div><label for="username">Pseudo:</label></div>
					<input type="text" id="username" name="pseudo" required />
				</div>
			{/if}
			<div class="form-line">
				<div><label for="email">Email:</label></div>
				<input type="text" id="email" name="email" required />
			</div>
			<div class="form-line">
				<div><label for="password">Mot de passe:</label></div>
				<input type="password" id="password" name="password" required />
			</div>
			{#if switchActive == 1}
				<div
					class="form-line"
					transition:fadeScale={{
						delay: 0,
						duration: 400,
						easing: cubicInOut,
						baseScale: 0.5
					}}
				>
					<div><label for="passwordConfirm">Confirmer:</label></div>
					<input type="password" id="passwordConfirm" name="passwordConfirm" required />
				</div>
				<div>
					<Button callback={() => (showModal = true)} label="avatar" />
				</div>
				<div>
					{#if croppedImage}
						<img src={croppedImage} alt="Cropped profile" class="avatar-preview" />
						<!-- Hidden input to submit cropped image as data URL -->
						<input type="file" name="avatar" style="display:none" />
					{:else}
						<p>Aucune image</p>
					{/if}
				</div>
			{/if}
			<!-- TODO disabled controlled by form validation -->
			<Button callback={handleSubmit} label="valider" disabled={false} />
		</form>
	</Box>
	{#if data?.error}
		<div>Error :{data?.error}</div>
	{/if}
</div>

<CropperModal bind:showModal bind:croppedImage bind:mimeType bind:blob />

<style>
	.login-page {
		width: fit-content;
		margin: auto;
	}
	.form-line {
		display: flex;
		justify-content: space-between;
		align-items: center;
		column-gap: 30px;
	}
	.form-line div {
		width: 100%;
	}
	.form-line label {
		width: 100px;
		text-align: right;
	}
	.form-line input {
		width: 200px;
	}
	.avatar-preview {
		width: 100px;
		height: 100px;
		border-radius: 50%;
		margin: auto;
		display: block;
	}
</style>

// src/components/LoginForm/LoginForm.tsx
import { useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Switch } from '../Switch/Switch';
import { Box } from '../Box/Box';
import { Button } from '../Button/Button';
import { useContext } from 'react';
import { AppContext } from '../../contexts/appContext';
import { CropperModal } from '../CropperModal/CropperModal';
import './loginForm.css'

export function LoginForm() {
  const appContext = useContext(AppContext);
  const navigate = useNavigate();
  const [firstIsActive, setfirstIsActive] = useState(true);
  const [croppedImage, setCroppedImage] = useState<string>('');
  const [isOpen, setIsOpen] = useState<boolean>(false);
  const formRef = useRef(null);
  const switchIndex = () => {
    setfirstIsActive(!firstIsActive)
  }
  
  const extension: {[index: string]:string} = {
		'image/gif': 'gif',
    'image/png': 'png',
		'image/jpeg': 'jpg'
	};

  const handleSubmit = async (formData : FormData) => {
    
    //? convert to json ( no image to process )
    //? remove register fields ( they'll be present for animation purpose )
    if(firstIsActive) {
      formData.delete("pseudo");
      formData.delete("passwordConfirm");
      formData.delete("avatar");
    }
    const json = JSON.stringify(Object.fromEntries(formData));

    if(!firstIsActive && croppedImage) {
      const blob = await fetch(croppedImage).then((r) => r.blob());
      const mimeType = croppedImage.substring(
				croppedImage.indexOf(':') + 1,
				croppedImage.indexOf(';')
			);
      const file = new File([blob], `avatar.${extension[mimeType]}`, {
				type: mimeType || 'image/png'
			});
			formData.set('avatar', file);
    }

    //TODO error handling

    // fetch
    const response: {accessToken: string, user: {id: number, pseudo: string, avatarUrl: string | null}} = await fetch(`http://localhost:3000/auth/${firstIsActive ? 'login' : 'register'}`, {
			method: 'POST',
			headers: firstIsActive ? {
				'Content-Type': 'application/json'
			} : undefined,
			body: firstIsActive ? json : formData
		}).then((res) => res.json());

    localStorage.setItem('accessToken', response.accessToken);
    localStorage.setItem('userInfos', JSON.stringify(response.user));
    appContext.setAppState({accessToken: response.accessToken, user: response.user});
    navigate('/');
  }

  return (
    <>
    <CropperModal setImage={setCroppedImage} croppedImage={croppedImage} showModal={isOpen} setShowModal={setIsOpen} />
    <div className='login-page'>
      <Switch
        labels={['login', 'register']}
        switchIndex={switchIndex}
        firstIsActive={firstIsActive}
      />
      <Box>
        {/* <form ref={formRef} action={handleSubmit}> */}
        <form ref={formRef}  action={handleSubmit}>
          {!firstIsActive && 
            /**
             * TODO : Make it a controlled input
             * and, in the handleChange, try to make an API call to check if pseudo is un use
             * ! Debounce it !
             */
            <div
              className="form-line"
            >
              <div><label htmlFor="username">Pseudo:</label></div>
              <input type="text" id="username" name="pseudo" required />
            </div>
          }
          <div className="form-line">
            <div><label htmlFor="email">Email:</label></div>
            <input type="text" id="email" name="email" required />
          </div>
          <div className="form-line">
            <div><label htmlFor="password">Mot de passe:</label></div>
            <input type="password" id="password" name="password" required />
          </div>
          {!firstIsActive && 
            <>
              <div
                className={`form-line ${!firstIsActive ? 'animated' : ''}`}
              >
                <div><label htmlFor="passwordConfirm">Confirmez:</label></div>
                <input type="password" id="passwordConfirm" name="passwordConfirm" required />
              </div>
              <div>
                <Button callback={() => (setIsOpen(true))} label="avatar" />
              </div>
              {croppedImage && 
                <>
                  <img src={croppedImage} alt="Cropped profile" className="avatar-preview" />
                </>
              }
            </>
          }
          <Button type='submit' label="Valider"/>
        </form>
      </Box>
    </div>
    </>
  )
}
